# Generated by Django 5.1.2 on 2024-10-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("breed", models.CharField(max_length=50)),
                ("years_of_experience", models.PositiveIntegerField()),
                ("salary", models.PositiveIntegerField()),
            ],
        ),
    ]
